package:
  name: onnxruntime
  version: 1.24.2
source:
  url: https://files.pythonhosted.org/packages/0a/bd/fca80d282bca9848b2c8e101c764432dd61a0e9d2377d1c8b3bab13235d0/onnxruntime-1.24.2-cp314-cp314-win_amd64.whl
  sha256: 71033c45db9fb677a0b7eb517a4ce70ae09258490e419b0e7f00d1e386ecb1b4
requirements:
  run: []
test:
  imports:
    - onnxruntime
about:
  home: https://github.com/microsoft/onnxruntime
  PyPI: https://pypi.org/project/onnxruntime
  summary: ONNX Runtime is a runtime accelerator for Machine Learning models
  license: MIT
