package:
  name: protobuf
  version: 6.30.0rc1
  top-level:
    - google

source:
  url: https://files.pythonhosted.org/packages/1f/de/3ab60cd4d8205267fb8d6425fecb1ce3a1b6c69567c6fa53b1f4e14e936e/protobuf-6.30.0rc1.tar.gz
  sha256: 4c309b8831fcfe6d815966122598e6141ef12563b9f3975676a07e2a8ceb368f

about:
  home: https://github.com/protocolbuffers/protobuf
  PyPI: https://pypi.org/project/protobuf
  summary: Protocol Buffers are a language-neutral, platform-neutral extensible mechanism for serializing structured data
  license: BSD-3-Clause

build:
  cflags: "-Wno-int-conversion"

extra:
  recipe-maintainers:
    - bartbroere
