package:
  name: protobuf
  version: 6.30.1
  top-level:
    - google

source:
  url: https://files.pythonhosted.org/packages/55/de/8216061897a67b2ffe302fd51aaa76bbf613001f01cd96e2416a4955dd2b/protobuf-6.30.1.tar.gz
  sha256: 535fb4e44d0236893d5cf1263a0f706f1160b689a7ab962e9da8a9ce4050b780

about:
  home: https://github.com/protocolbuffers/protobuf
  PyPI: https://pypi.org/project/protobuf
  summary: Protocol Buffers are a language-neutral, platform-neutral extensible mechanism for serializing structured data
  license: BSD-3-Clause

build:
  cflags: "-Wno-int-conversion"

extra:
  recipe-maintainers:
    - bartbroere
